### ISSUE TITLE
ezspin also knits to md/html 

### ISSUE THREAD

**Issue by mitcda** [daattali/ezknitr#16]
I'm trying to ezknitr to produce multiple Rmd files multiple code files, which I can then use process via bookdown to produce gitbook and PDF outputs. At present, `ezspin()` both spins __and knits__ the Rmd file to md/html, which doesn't appear to be the purpose of the function. It appears to me that the closing brace at line 290 in `core.R` should be after current line 296 (see below).

```
288  } else if (type == "ezknit") {
289    file_rmd <- file
290  }                                      # <- Suggest this brace ...
291  knitr::knit(file_rmd,
292              file_md,
293              quiet = !verbose,
294              envir = ezknitr_env)
295  markdown::markdownToHTML(file_md,
296                           file_html)
                                           # <- .. should be here
```

**Comment by daattali** [comment]
It's on purpose that knitting happens, to give the user maximum flexibility. You can choose which types of outputs are kept. Use the `keep_md` and/or `keep_html` parameters to not have those files at the end. But we don't want to always disable them for everyone.
