### ISSUE TITLE
Minor bug report - path length too long

### ISSUE THREAD

**Issue by jzadra** [daattali/ezknitr#17]
I encountered a warning running `ezknit()`:

```
ezknit("table_structuring.Rmd", out_dir = "output/2023 Q1Q2/")

ezknit output in
/Users/myuser12/Documents/R Projects/8413_nsjhfie_report_automation/output/2023 Q1Q2
Warning message:
In file.info(x, extra_cols = FALSE) :
  expanded path length 66479 would be too long for
```
(message was truncated as shown above)

It didn't seem to affect the output.

**Comment by daattali** [comment]
Thanks for the report. I'm curious why the path claims to be 66479 characters long. Does this happen even if you have a trivial Rmd?

**Comment by jzadra** [comment]
I just ran it on RStudio's default Rmarkdown template, and got the same warning, as well as oddly printing some of the html to the console.  The output was normal:

```r
> ezknit("Untitled.Rmd", out_dir = "~/temp")
ezknit output in
/Users/myuser12/temp
Warning message:
In file.info(x, extra_cols = FALSE) :
  expanded path length 1145 would be too long for
<h2 id="r-markdown">R Markdown</h2>
<p>This is an R Markdown document. Markdown is a simple formatting syntax for authoring HTML, PDF, and MS Word documents. For more details on using R Markdown see <a href="http://rmarkdown.rstudio.com">http://rmarkdown.rstudio.com</a>.</p>
<p>When you click the <strong>Knit</strong> button a document will be generated that includes both content as well as the output of any embedded R code chunks within the document. You can embed an R code chunk like this:</p>
<pre><code class="language-r">summary(cars)
</code></pre>
<pre><code>##      speed           dist       
##  Min.   : 4.0   Min.   :  2.00  
##  1st Qu.:12.0   1st Qu.: 26.00  
##  Median :15.0   Median : 36.00  
##  Mean   :15.4   Mean   : 42.98  
##  3rd Qu.:19.0   3rd Qu.: 56.00  
##  Max.   :25.0   Max.   :120.00
</code></pre>
<h2 id="including-plots">Including Plots</h2>
<p>You can also embed plots, for example:</p>
<p><img src="Untitled//pre [... truncated]
> 
```

It does the same thing in a clean, standalone R console, so it's not RStudio.

setting  value
 version  R version 4.3.0 (2023-04-21)
 os       macOS 14.0
 system   aarch64, darwin20
 ui       RStudio
 language (EN)
 collate  en_US.UTF-8
 ctype    en_US.UTF-8
 tz       America/Los_Angeles
 date     2023-10-02
 rstudio  2023.06.0+421 Mountain Hydrangea (desktop)
 pandoc   3.1.1 @ /Applications/RStudio.app/Contents/Resources/app/quarto/bin/tools/ (via rmarkdown)

**Comment by daattali** [comment]
Which version of {ezknitr} are you using, and can you attach the .Rmd file to your next message?

**Comment by daattali** [comment]
For reference, I just reformatted my own PC this week, so I just installed ezknitr (0.6.3) from scratch and ran it on RStudio's default Rmd. This is the output:

```r
> ezknitr::ezknit("Untitled.Rmd", out_dir = "~/temp")
ezknit output in
C:\Users\Dean\Documents\temp
```

I also tried running it on a RStudio Server running on a linux machine, and got the same short output. Perhaps it's a Mac issue, do you have access to another machine to test?

**Comment by jzadra** [comment]
I'm using 0.6.3.  

[Untitled.Rmd.zip](https://github.com/ropensci/ezknitr/files/12797241/Untitled.Rmd.zip)

I tested it on a PC and had no issue.

I unpacked the `ezknit_helper()` function and went through it line by line with my Rmd.  The problem occurs on line 111:
`markdown::markdownToHTML(file_md, file_html)`.  I've stopped tracing there because I'm out of time today, but if this is helpful enough for you to track it, great, if not let me know and I'll try to trace it further.

I've also doublechecked the expanded path and it's 110 characters - OSX can handle up to 255.

**Comment by daattali** [comment]
You mean these lines? https://github.com/ropensci/ezknitr/blob/4bd1832a7bea661816bc9c1777b2f85d1dd7a594/R/core.R#L295-L296

Thanks for troubleshooting. If it works for you on other systems, then it does sound like a Mac issue. I don't have a Mac available to me for testing, so it'll be a while before I can get my hands on one to debug.

If you could try running `markdown::markdownToHTML()` in a fresh session, and let me know if that works or not, that would really help.

**Comment by jzadra** [comment]
Those are the lines I'm referring to. Not sure where I got line 111 from.

I have tested `markdown::markdownToHTML()` in a fresh session, and I get the same error.  I will start an issue on their github.... and it looks like a recent update fixed this: [https://github.com/rstudio/markdown/issues/103](url)

**Comment by daattali** [comment]
Great, thanks for catching!
