### ISSUE TITLE
Add missing `spin` arguments

### ISSUE THREAD

**Issue by klmr** [daattali/ezknitr#6]
`knitr::spin` supports a number of arguments to customise the handling of the file. In particular, it allows specifying the comment prefix regex (default `"^#+'[ ]?"`). I need to change this argument since my document is using a different prefix (the default is inconvenient since my editor recognises it as a roxygen comment and attempts to highlight it incorrectly).

`ezspin` currently doesn’t handle these arguments. This should be changed.

**Comment by daattali** [comment]
What do you think of adding a `...` parameter to `ezspin` that will simply pass on its parameters to `spin`, so that you could specify any other arguments spin might have such as `doc`, `inline`, and `comment`?

**Comment by klmr** [comment]
Yeah, that’s probably the cleanest option. However, the problem at the moment is that both `ezspin` and `ezknit` call the same function internally, so you’d need to take care to dispatch `...` to the right call. In my case, I’d prefer to call `spin` without `knit` anyway, since knitting itself is down by RMarkdown. But that requires even more configuration and doesn’t really warrant the “ez” prefix any more. 😛

**Comment by daattali** [comment]
I don't think it'll be too hard to make the `...` argument work and just ignore it in the knit case.  Feel free to send a PR, otherwise I'll try to do this at some point when I have an hour to kill

**Comment by daattali** [comment]
@klmr can you see if my fix does what you expected?

**Comment by klmr** [comment]
Thanks, that seems to work very well.
